# Generated by Django 5.2.8 on 2025-11-15 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIN', models.CharField(max_length=20, unique=True)),
                ('selfie_with_id', models.ImageField(upload_to='agent_selfies/')),
                ('guarantor_name', models.CharField(max_length=255)),
                ('guarantor_contact', models.CharField(max_length=20)),
                ('guarantor_address', models.CharField(max_length=255)),
                ('relation_to_guarantor', models.CharField(max_length=100)),
                ('guarantor_passport_photo', models.ImageField(upload_to='guarantor_photos/')),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
