# Generated by Django 5.2.8 on 2025-11-16 19:41

import agent.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='guarantor_passport_photo',
            field=models.ImageField(help_text='Maximum file size: 5MB', upload_to='guarantor_photos/', validators=[agent.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='selfie_with_id',
            field=models.ImageField(help_text='Maximum file size is 5MB', upload_to='agent_selfies/', validators=[agent.validators.validate_file_size]),
        ),
    ]
